import './globals.css';
import type { Metadata } from 'next';
import Footer from "../components/footer/page"
import { Header } from "../components/header/page"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
